version: '2.3'

services:
  minning-pool-api:
    build: .
    ports:
      - 9090:9090
    environment:
      DATABASE_URL: postgres://postgres:pass@postgres-docker/mining_pool_api
    depends_on:
      - postgres
  
  postgres:
    image: postgres:latest
    hostname: postgres-docker
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mining_pool_api
    volumes:
        - ./migrations/2024-04-23-105958_mining_pool_api/up.sql:/docker-entrypoint-initdb.d/up.sql